Pad: IOPADS_INST/PAD_clock_i S ICP
Pad: IOPADS_INST/PAD_reset_i S ICP
Pad: IOPADS_INST/PAD_boot_address0_o N ICP
Pad: IOPADS_INST/PAD_boot_address1_o N ICP
Pad: IOPADS_INST/PAD_boot_address2_o N ICP
Pad: IOPADS_INST/PAD_boot_address3_o N ICP
Pad: IOPADS_INST/PAD_boot_address4_o N ICP
Pad: IOPADS_INST/PAD_boot_address5_o N ICP
Pad: IOPADS_INST/PAD_boot_address6_o N ICP
Pad: IOPADS_INST/PAD_boot_address7_o N ICP
Pad: IOPADS_INST/PAD_boot_address8_o N ICP
Pad: IOPADS_INST/PAD_boot_address9_o N ICP
Pad: IOPADS_INST/PAD_boot_address10_o N ICP
Pad: IOPADS_INST/PAD_boot_address11_o N ICP
Pad: IOPADS_INST/PAD_boot_address12_o N ICP
Pad: IOPADS_INST/PAD_boot_address13_o N ICP
Pad: IOPADS_INST/PAD_boot_address14_o N ICP
Pad: IOPADS_INST/PAD_boot_address15_o N ICP
Pad: IOPADS_INST/PAD_boot_address16_o N ICP
Pad: IOPADS_INST/PAD_boot_address17_o N ICP
Pad: IOPADS_INST/PAD_boot_address18_o N ICP
Pad: IOPADS_INST/PAD_boot_address19_o N ICP
Pad: IOPADS_INST/PAD_boot_address20_o N ICP
Pad: IOPADS_INST/PAD_boot_address21_o N ICP
Pad: IOPADS_INST/PAD_boot_address22_o N ICP
Pad: IOPADS_INST/PAD_boot_address23_o N ICP
Pad: IOPADS_INST/PAD_boot_address24_o N ICP
Pad: IOPADS_INST/PAD_boot_address25_o N ICP
Pad: IOPADS_INST/PAD_boot_address26_o N ICP
Pad: IOPADS_INST/PAD_boot_address27_o N ICP
Pad: IOPADS_INST/PAD_boot_address28_o N ICP
Pad: IOPADS_INST/PAD_boot_address29_o N ICP
Pad: IOPADS_INST/PAD_boot_address30_o N ICP
Pad: IOPADS_INST/PAD_boot_address31_o N ICP
Pad: IOPADS_INST/PAD_instruction_in0_o W ICP
Pad: IOPADS_INST/PAD_instruction_in1_o W ICP
Pad: IOPADS_INST/PAD_instruction_in2_o W ICP
Pad: IOPADS_INST/PAD_instruction_in3_o W ICP
Pad: IOPADS_INST/PAD_instruction_in4_o W ICP
Pad: IOPADS_INST/PAD_instruction_in5_o W ICP
Pad: IOPADS_INST/PAD_instruction_in6_o W ICP
Pad: IOPADS_INST/PAD_instruction_in7_o W ICP
Pad: IOPADS_INST/PAD_instruction_in8_o W ICP
Pad: IOPADS_INST/PAD_instruction_in9_o W ICP
Pad: IOPADS_INST/PAD_instruction_in10_o W ICP
Pad: IOPADS_INST/PAD_instruction_in11_o W ICP
Pad: IOPADS_INST/PAD_instruction_in12_o W ICP
Pad: IOPADS_INST/PAD_instruction_in13_o W ICP
Pad: IOPADS_INST/PAD_instruction_in14_o W ICP
Pad: IOPADS_INST/PAD_instruction_in15_o W ICP
Pad: IOPADS_INST/PAD_instruction_in16_o W ICP
Pad: IOPADS_INST/PAD_instruction_in17_o W ICP
Pad: IOPADS_INST/PAD_instruction_in18_o W ICP
Pad: IOPADS_INST/PAD_instruction_in19_o W ICP
Pad: IOPADS_INST/PAD_instruction_in20_o W ICP
Pad: IOPADS_INST/PAD_instruction_in21_o W ICP
Pad: IOPADS_INST/PAD_instruction_in22_o W ICP
Pad: IOPADS_INST/PAD_instruction_in23_o W ICP
Pad: IOPADS_INST/PAD_instruction_in24_o W ICP
Pad: IOPADS_INST/PAD_instruction_in25_o W ICP
Pad: IOPADS_INST/PAD_instruction_in26_o W ICP
Pad: IOPADS_INST/PAD_instruction_in27_o W ICP
Pad: IOPADS_INST/PAD_instruction_in28_o W ICP
Pad: IOPADS_INST/PAD_instruction_in29_o W ICP
Pad: IOPADS_INST/PAD_instruction_in30_o W ICP
Pad: IOPADS_INST/PAD_instruction_in31_o W ICP
Pad: IOPADS_INST/PAD_data_in0_o W ICP
Pad: IOPADS_INST/PAD_data_in1_o W ICP
Pad: IOPADS_INST/PAD_data_in2_o W ICP
Pad: IOPADS_INST/PAD_data_in3_o W ICP
Pad: IOPADS_INST/PAD_data_in4_o W ICP
Pad: IOPADS_INST/PAD_data_in5_o W ICP
Pad: IOPADS_INST/PAD_data_in6_o W ICP
Pad: IOPADS_INST/PAD_data_in7_o W ICP
Pad: IOPADS_INST/PAD_data_in8_o W ICP
Pad: IOPADS_INST/PAD_data_in9_o W ICP
Pad: IOPADS_INST/PAD_data_in10_o W ICP
Pad: IOPADS_INST/PAD_data_in11_o W ICP
Pad: IOPADS_INST/PAD_data_in12_o W ICP
Pad: IOPADS_INST/PAD_data_in13_o W ICP
Pad: IOPADS_INST/PAD_data_in14_o W ICP
Pad: IOPADS_INST/PAD_data_in15_o W ICP
Pad: IOPADS_INST/PAD_data_in16_o W ICP
Pad: IOPADS_INST/PAD_data_in17_o W ICP
Pad: IOPADS_INST/PAD_data_in18_o W ICP
Pad: IOPADS_INST/PAD_data_in19_o W ICP
Pad: IOPADS_INST/PAD_data_in20_o W ICP
Pad: IOPADS_INST/PAD_data_in21_o W ICP
Pad: IOPADS_INST/PAD_data_in22_o W ICP
Pad: IOPADS_INST/PAD_data_in23_o W ICP
Pad: IOPADS_INST/PAD_data_in24_o W ICP
Pad: IOPADS_INST/PAD_data_in25_o W ICP
Pad: IOPADS_INST/PAD_data_in26_o W ICP
Pad: IOPADS_INST/PAD_data_in27_o W ICP
Pad: IOPADS_INST/PAD_data_in28_o W ICP
Pad: IOPADS_INST/PAD_data_in29_o W ICP
Pad: IOPADS_INST/PAD_data_in30_o W ICP
Pad: IOPADS_INST/PAD_data_in31_o W ICP
Pad: IOPADS_INST/PAD_interrupt_request_external_i N ICP
Pad: IOPADS_INST/PAD_interrupt_request_timer_i N ICP
Pad: IOPADS_INST/PAD_interrupt_request_software_i N ICP



Pad: IOPADS_INST/PAD_vdd_E E VDDORPADP
Pad: IOPADS_INST/PAD_vdd_core_E E VDDPADP
Pad: IOPADS_INST/PAD_vdd_core_N N VDDPADP
Pad: IOPADS_INST/PAD_vss_core_N N GNDORPADP
Pad: IOPADS_INST/PAD_vss_W W GNDORPADP
Pad: IOPADS_INST/PAD_vss_S S GNDORPADP

Pad: IOPADS_INST/PAD_corner_lr SE CORNERP
Pad: IOPADS_INST/PAD_corner_ll SW CORNERP
Pad: IOPADS_INST/PAD_corner_ur NE CORNERP
Pad: IOPADS_INST/PAD_corner_ul NW CORNERP

